### ISSUE TITLE
关于 Problem 2.2

### ISSUE THREAD

**Issue by RingoTC** [Doraemonzzz/Learning-from-data#1]
![Problem 2.2](https://upload-images.jianshu.io/upload_images/2544913-5738ecbe5e0aad85.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

我的做法是，根据 $m_H(5) < 2^5$得到 break point为5，则 $d_{vc}=4$。
然后就得到，$m_H(N) \leq N^4+1$

**Comment by Doraemonzzz** [comment]
对，感觉题意好像确实是这个意思，我修改下。

**Comment by Doraemonzzz** [comment]
已修改并上传。
