### ISSUE TITLE
Exercise 2.2(b)可以画图来更好理解

### ISSUE THREAD

**Issue by laichang** [Doraemonzzz/Learning-from-data#4]
N = 1:15;
y1 = N + 2^floor(N/2);
y2 = 1 + 1/2*N + 1/2*N*N;
plot(N,y1,N,y2);  % 可以看到会有交叉的地方

**Comment by Doraemonzzz** [comment]
嗯，也可以，因为break point为3

**Comment by Doraemonzzz** [comment]
感谢指出，已添加修改。
