### ISSUE TITLE
Exercise 1.10 (b)

### ISSUE THREAD

**Issue by czfyy** [Doraemonzzz/Learning-from-data#5]
抱歉打扰，Exercise 1.10 (b)中 E[vmin] 的推导我有些疑问：
1. E[vmin] = E[ min(X1, X2, ... , X1000)] 这个公式中，左边vmin是概率值，右侧min()是取值最小事件，这个等式写法是不是有点问题？还是我对vmin的理解有误？            
2. vmin作为正面向上的概率，其分布列已知。可我不太清楚分布函数P(vmin < k/10)中k/10是代表什么意思呢？           
问题有点蠢，抱歉打扰

**Comment by Doraemonzzz** [comment]
1.vmin是样本的最小值，是一个随机变量，根据定义有vmin=min(X1, X2, ... , X1000)，然后对该随机变量取期望即可
2.由题意可知，vmin为投10次正面的比例，这里k为正面的次数，分母10为投掷的次数，所以计算vmin<k/10的概率比较方便

不知是否解释清楚，有问题的话可以继续讨论。

**Comment by czfyy** [comment]
> 1.vmin是样本的最小值，是一个随机变量，根据定义有vmin=min(X1, X2, ... , X1000)，然后对该随机变量取期望即可
> 2.由题意可知，vmin为投10次正面的比例，这里k为正面的次数，分母10为投掷的次数，所以计算vmin<k/10的概率比较方便
> 
> 不知是否解释清楚，有问题的话可以继续讨论。

我再考虑一下，谢谢 :D

**Comment by czfyy** [comment]
> 1.vmin是样本的最小值，是一个随机变量，根据定义有vmin=min(X1, X2, ... , X1000)，然后对该随机变量取期望即可
> 2.由题意可知，vmin为投10次正面的比例，这里k为正面的次数，分母10为投掷的次数，所以计算vmin<k/10的概率比较方便
> 
> 不知是否解释清楚，有问题的话可以继续讨论。

应该明白了，我再研究研究，谢谢 :D
