### ISSUE TITLE
Problem 3.14 (a), bias question.

### ISSUE THREAD

**Issue by sharov-am** [Doraemonzzz/Learning-from-data#7]
Hi.

Thank you very much for your work and this git repo. I have few questions about Problem 3.14(a):

1)Why did you squred the bias? From wiki on bias : "Bias is difference between this estimator's expected value and the true value of the parameter being estimated". So why to square it?
2) I think the answer for bias you  obtain is wrong, because linear regression (OLS) is unbiased estimator, hence bias should be null. If you didn't do squaring then you would obtain correct result.

**Comment by Doraemonzzz** [comment]
> Hi.
> 
> Thank you very much for your work and this git repo. I have few questions about Problem 3.14(a):
> 
> 1)Why did you squred the bias? From wiki on bias : "Bias is difference between this estimator's expected value and the true value of the parameter being estimated". So why to square it?
> 2) I think the answer for bias you obtain is wrong, because linear regression (OLS) is unbiased estimator, hence bias should be null. If you didn't do squaring then you would obtain correct result.

Sorry for the late reply.
I think that in this book, bias means bias^2 in other literature, where the author mentioned in the footer on page 64
> What we call bias is sometimes called bias^2 in the literature
