### ISSUE TITLE
请求资源

### ISSUE THREAD

**Issue by rentainhe** [Doraemonzzz/Learning-from-data#8]
请问有这本书的pdf电子版吗，跪谢

**Comment by Doraemonzzz** [comment]
> 请问有这本书的pdf电子版吗，跪谢

链接：https://pan.baidu.com/s/1Mftwyou9v9Rjg8qUff2HbQ 
提取码：caw0

**Comment by rentainhe** [comment]
哭了哭了，非常感谢
